# Generated by Django 3.1 on 2020-08-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_auto_20200828_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='question',
        ),
        migrations.AddField(
            model_name='result',
            name='study_material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='language.studymaterial'),
            preserve_default=False,
        ),
    ]
