# Generated by Django 3.1 on 2020-09-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0004_searchquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='brief_description',
            field=models.TextField(blank=True, verbose_name='Brief Description'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=2, verbose_name='Number'),
        ),
    ]
