# Generated by Django 3.1 on 2020-08-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
