# Generated by Django 3.1 on 2020-09-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_auto_20200829_1807'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='language.Language'),
        ),
    ]
