# Generated by Django 3.1 on 2020-09-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0004_searchquery'),
        ('user', '0003_auto_20200902_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='language.Language'),
        ),
    ]
